### ISSUE TITLE
error: Invalid Cache.

### ISSUE THREAD

**Issue by sdrobert** [LaTeXing/LaTeXing#103]
Hello,

I'm using Sublime Text 3 with LaTeXing on Ubuntu. Every time I try to enter \usepackage or \documentclass, I receive the error: "Invalid cache data, please reset the cache!"

This happened after I tried to hard rebuild the cache once. Now I've tried rebuilding the cache (both hard and soft). This doesn't seem to work.

Thanks,
Sean

**Comment by csch0** [comment]
Was this ever working before??

**Comment by sdrobert** [comment]
Yes. Perhaps this is post update, though.

I also receive this message in the error logs:

Exception in thread Thread-46:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Development/latexing/progress.py", line 16, in run
  File "/Development/latexing/viewer.py", line 59, in <lambda>
  File "/Development/latexing/viewer.py", line 223, in __run
  File "/Development/latexing/viewer.py", line 220, in check_program
  File "/Development/latexing/terminal.py", line 362, in communicate
  File "/Development/latexing/terminal.py", line 396, in popen
UnboundLocalError: local variable 'proc' referenced before assignment

But this seems related to the viewer, not the cache.

**Comment by csch0** [comment]
Ok I think its an issue related to #101 and #101 so could you please update to 1.2.6 and check it again. Thanks! Might take about an hour until the update is visible due to the package control delay.

**Comment by sdrobert** [comment]
Updated. Seems to work now! Neither message shows.
