### ISSUE TITLE
LaTeXing 1.2.8 Installation Problems

### ISSUE THREAD

**Issue by ddauer** [LaTeXing/LaTeXing#111]
All I get is `Unable to find target command: ltx_default_compiler` when hitting Cmd+B.

**Comment by csch0** [comment]
Please try this one: #109

**Comment by ddauer** [comment]
alright, reinstalling Latexing at 1.2.8 made the build system work again. 

now, however, I'm getting 
`Package Control The package specified, oauthlib, is not available` with Package Control at v3.0.1 on OS X 10.10.2.

**Comment by csch0** [comment]
ok here please try #106

One time effort after so many internal changes in LaTeXing this version.

**Comment by ddauer** [comment]
thanks a lot! after removing the oauthlib directory and the entry from Package Control.sublime-settings manually, things seem to be working again.

**Comment by csch0** [comment]
Thanks for the feeback! Yes you are not the first one. Looks like this update needs some one time manual work too.

Will reopen this issue open for other people so they find the solution faster.

**Comment by sunew** [comment]
These solutions do not seem to work for me. After removing / reinstalling latexing, and removing oauthlib from packagecontrol settings, I get this error during sublime startup:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "LaTeXing in /home/sune/.config/sublime-text-3/Installed Packages/LaTeXing.sublime-package", line 4, in <module>
  File "/Development/latexing/__init__.py", line 16, in <module>
  File "/Development/latexing/cache.py", line 19, in <module>
  File "/Development/latexing/api/mendeley.py", line 9, in <module>
  File "/home/sune/.config/sublime-text-3/Packages/requests-oauthlib/all/requests_oauthlib/__init__.py", line 3, in <module>
    from .oauth2_auth import OAuth2
  File "/home/sune/.config/sublime-text-3/Packages/requests-oauthlib/all/requests_oauthlib/oauth2_auth.py", line 3, in <module>
    from oauthlib.oauth2 import is_secure_transport
ImportError: cannot import name is_secure_transport

**Comment by sunew** [comment]
Okay, things are working again:)

To summarize:

1) browse packages -> remove the folders oauthlib and requests-oauthlib
2) remove latexing with package control
3) install latexing with package control
4) restart sublime - check the console for errors

**Comment by csch0** [comment]
Thanks @sunew to share your way of getting it to work. :+1:

**Comment by drevicko** [comment]
for those on mac osx, the packages folder is here:

  ~/Library/Application Support/Sublime Text 3/Packages

@sunew your steps worked (: Thx! My thesis can continue it's mad rush to it's long awaited end! ;)

@csch0  perhaps those steps could be highlighted in a faq or somewhere? some may not find it here easily, and I suspect many are affected by this...

**Comment by arturalkaim** [comment]
I'm having a similar error:

reloading plugin LaTeXing.LaTeXing
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "LaTeXing in /Users/arturalkaim/Library/Application Support/Sublime Text 3/Installed Packages/LaTeXing.sublime-package", line 4, in <module>
  File "/Development/latexing/__init__.py", line 15, in <module>
  File "/Development/latexing/check_system.py", line 5, in <module>
ImportError: No module named 'tabulate'

**Comment by iekanat** [comment]
The issue persisted for me after carrying out steps outlined here. I found out that having pandoc installed messes things up. 

I like using pandoc to create pdf documents from md's... So I hope a solution will be found.
