### ISSUE TITLE
Suddenly not able to access Mendeley

### ISSUE THREAD

**Issue by rudvfaden** [LaTeXing/LaTeXing#116]
I have been using Mendeley for a long time without any problems. But today, I keep getting a error messages that LaTeXing could not access Mendeley

**Comment by csch0** [comment]
Cannot confirm that, if it was still working after yesterday's update then this is most likely a Mendeley and not directly related to LaTeXing

**Comment by rudvfaden** [comment]
Strangely it works on my mac but not on my linux pc

**Comment by csch0** [comment]
I cannot see any issue even on Linux, do you get any error message in the console?

**Comment by rudvfaden** [comment]
When I  try to update the bibliography I get the following error

![error1](https://cloud.githubusercontent.com/assets/2445577/6582963/2baff444-c761-11e4-82f9-a9cd20c657f8.png)

and the console says

    [Accessing Mendeley.com]

    Checked Mendeley access and access denied

    [Done]

**Comment by csch0** [comment]
Yes was talking about the python console in Sublime text? Did you tried to re-authorise mendeley?

**Comment by rudvfaden** [comment]
The sublime console just says the same thing. Yes, I reactivated many times.

**Comment by csch0** [comment]
please enable the log setting of LaTeXing. There should be more.. :)

**Comment by rudvfaden** [comment]
```
LTX DEBUG cache.py:756 run /home/rudfaden/Dropbox/PhD/information-and-care/Main/Remote.bib
LTX DEBUG cache.py:756 run /home/rudfaden/Dropbox/PhD/information-and-care/Main/Remote.bib
LTX DEBUG cite.py:93 fetch_cites {'data': ['normal', 'tag', 'folder', 'missing'], 'id': 'mendeley'}
LTX DEBUG cache.py:178 is_cache_outdated mendeley.cache 01.01.2000T00:00:00
LTX ERROR mendeley.py:221 run super(type, obj): obj must be an instance or subtype of type
error: Cannot access Mendeley.com, please check docs.latexing.com for more details
```

**Comment by csch0** [comment]
Could youu update and just try it again with 1.2.10-rc.2? Should give you a real raise of the exception.

**Comment by rudvfaden** [comment]
Do you mean that I should install the developer version?

**Comment by csch0** [comment]
yes please, also to check #105 you know how?

**Comment by rudvfaden** [comment]
Now I

    Checked Mendeley and no remote items available

and there is nothing in the .bib file.

The console says
```
LTX DEBUG cache.py:756 run /home/rudfaden/Dropbox/PhD/Moral hazard and risk spreading/application/Remote.bib
LTX DEBUG cite.py:93 fetch_cites {'data': ['normal', 'tag', 'folder', 'missing'], 'id': 'mendeley'}
LTX DEBUG cache.py:178 is_cache_outdated mendeley.cache 01.01.2000T00:00:00
Exception in thread Thread-40:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Development/latexing/progress.py", line 16, in run
  File "/Development/latexing/cache.py", line 1192, in run
  File "/Development/latexing/api/mendeley.py", line 221, in run
  File "/Development/latexing/api/mendeley.py", line 167, in run
  File "/Development/latexing/api/mendeley.py", line 36, in get_access_token
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests-oauthlib/all/requests_oauthlib/oauth2_session.py", line 246, in refresh_token
    timeout=timeout, verify=verify)
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests-oauthlib/all/requests_oauthlib/oauth2_session.py", line 299, in request
    headers=headers, data=data, **kwargs)
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 610, in send
    r.content
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests/all/requests/models.py", line 730, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests/all/requests/models.py", line 655, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/response.py", line 273, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/response.py", line 203, in read
    data = self._fp.read(amt)
  File "./http/client.py", line 507, in read
TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by csch0** [comment]
Ok thats an issue by the request library which LaTeXing is using, was this ever working before on your system??

**Comment by rudvfaden** [comment]
It was working before `1.2.9`

**Comment by csch0** [comment]
Cannot really believe that tbh, changed nothing in that area, to check I uploaded the old 1.2.8 version here, just replace the package manually.

http://testing.latexing.com/old/LaTeXing.sublime-package

**Comment by rudvfaden** [comment]
I get the same error in 1.2.8 as in 1.2.9. Maybe i am remembering it wring, and it just worked for mac

**Comment by csch0** [comment]
Ok like before think it is a problem with the library, what Linux version do you use? I check Ubuntu 64bit 14.04.2.

But its very strange if oauth works but not the normal request.

**Comment by rudvfaden** [comment]
i am using elementary os freya. It is based on ubuntu 14.04 LTS 64 bit

**Comment by csch0** [comment]
Will just install this in the VM later and we will see.. normally should work!

**Comment by csch0** [comment]
So I checked it with a fresh installation an cannot reproduce any problem. Must be a problem on your configuratiob. So you might try to reinstall Sublime Text, clean all packages perhaps something went wrong.

**Comment by rudvfaden** [comment]
A reinstall made it work

**Comment by kellpossible** [comment]
I've just had this same problem
![Screenshot]
(http://i.imgur.com/u60EYI5.png)
