### ISSUE TITLE
LaTeXing does not accept valid Mendely OAuth tokens

### ISSUE THREAD

**Issue by gvoysey** [LaTeXing/LaTeXing#117]
Running the latest version for Sublime Text 3 on OSX 10.10.2. 

I have added the following to my `Latexing.sublime-settings User` file: 

```json
 {
   "mendeley": true,
    "mendeley_oauth_token": "",
    "mendeley_oauth_token_secret": "",
    "mendeley_internal_cite_key": false,
    "mendeley_cite_key_pattern": "{Author}{Year}{Title}",
}
```
I then open a `.tex` file. 

Running ⌘L-⌘R : 
1.  Prompts me to create `Remote.bib`, which I do. 
2.  launches the Mendeley authentication website, which I log into and which hands me a token. 
3.  Returning to Sublime, the `Please enter your verification code` prompt has a URL entered in the text field already, (which is `https://api.mendeley.com/oauth/authorize?response_type=code&client_id=141&scope=all&state=*****`  where *** is some hash that might identify me so i'm leaving it out. 
4.  I delete this text, and enter the OAuth token, and hit enter. 
5.  Nothing happens.  `Remote.bib` exists but is a 0-byte file. 
6.  From the sublime console: 
    
``` python
    Traceback (most recent call last):
  File "/Development/latexing/api/mendeley.py", line 213, in on_done
  File "/Development/latexing/api/mendeley.py", line 42, in get_refresh_token
  File "/Users/gvoysey/Library/Application Support/Sublime Text 3/Packages/requests-oauthlib/all/requests_oauthlib/oauth2_session.py", line 199, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/Users/gvoysey/Library/Application Support/Sublime Text 3/Packages/oauthlib/all/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/Users/gvoysey/Library/Application Support/Sublime Text 3/Packages/oauthlib/all/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "/Users/gvoysey/Library/Application Support/Sublime Text 3/Packages/oauthlib/all/oauthlib/oauth2/rfc6749/parameters.py", line 383, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/Users/gvoysey/Library/Application Support/Sublime Text 3/Packages/oauthlib/all/oauthlib/oauth2/rfc6749/errors.py", line 259, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Invalid access code
```

I have repeated this a few times, always with the same effect.  I get very similar results on my Windows 7 development box.

**Comment by csch0** [comment]
Develop LaTeXing on OSX, so if a system is well tested its this. I just tested it again and its working. So you are sure you deleted the old oauthlib package? Juts guessing here, since normally there is no problem.

**Comment by gvoysey** [comment]
I have only installed sublime 3 and LaTeXing.  I had to install LaTeXing manually because it wasn't showing up in the list of packages from the package manager (which is weird because it was on my windows machine yesterday). 

My list of installed sublime packages does not include oauthlib at all -- where can I check the version?

**Comment by csch0** [comment]
Perhaps because it was in your ignore list? No idea! Could you close Sublime Text, start it and post your console output here? So we can see if everything is there.

**Comment by gvoysey** [comment]
```python 
startup, version: 3065 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/gvoysey/Library/Application Support/Sublime Text 3/Packages
state path: /Users/gvoysey/Library/Application Support/Sublime Text 3/Local
hardware concurrency: 4
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/gvoysey/Library/Application Support/Sublime Text 3/Installed Packages
found 8 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 7 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 1 orphaned files: 0 total files: 198 cache hits: 197
pre session restore time: 0.426201
using gamma: 2 (err: 6.9282)
first paint time: 0.558224
startup time: 0.576709
launching: /Applications/Sublime Text.app/Contents/MacOS/plugin_host
loaded 899 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-oauthlib
reloading plugin 0_package_control_loader.50-requests
reloading plugin 0_package_control_loader.51-requests-oauthlib
reloading plugin Git.add
reloading plugin Git.annotate
reloading plugin Git.commit
reloading plugin Git.diff
reloading plugin Git.flow
reloading plugin Git.git
reloading plugin Git.history
reloading plugin Git.repo
reloading plugin Git.stash
reloading plugin Git.status
reloading plugin Git.statusbar
reloading plugin Github Tools.github
reloading plugin Github Tools.github_blame
reloading plugin Github Tools.github_copy_link
reloading plugin Github Tools.github_create_pr
reloading plugin Github Tools.github_issues
reloading plugin Github Tools.github_open
reloading plugin Github Tools.github_plugin_settings
reloading plugin Github Tools.github_pulls
reloading plugin Github Tools.github_repository
reloading plugin LaTeXing.LaTeXing
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Markmon real-time markdown preview.commands
reloading plugin Markmon real-time markdown preview.markmon
reloading plugin Markmon real-time markdown preview.MarkmonListener
reloading plugin Markmon real-time markdown preview.util
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin AutoSpell.AutoSpell
plugins loaded
Building AutoSpell Index: Started
Building AutoSpell Index: Finished
found 8 files for base name Default.sublime-keymap
Package Control: Skipping automatic upgrade, last run at 2015-03-11 10:44:57, next run at 2015-03-11 11:44:57 or after
```

**Comment by csch0** [comment]
All good... no idea what went wrong so far.

So inside the box in step 4 you entered the code from [here](http://www.latexing.com/mendeley.html?code=TESTCODE) or?

**Comment by gvoysey** [comment]
from `http://www.latexing.com/mendeley.html?state=SOME HASH&code=SOME OTHER HASH`

**Comment by csch0** [comment]
but you just use the "SOME OTHER HASH" which is the code the grey box..

**Comment by gvoysey** [comment]
It seems to work now -- i tried again.  I think that copying out the code from the text box includes an extra space and carriage return, which was throwing things off.  
I can now type `\cite{` and have an intellisense-like completeion of everything in my mendeley library.  
Thanks both for the help and for making this real -- i cannot even start to say how helpful this is for my daily writing.

**Comment by csch0** [comment]
Ok best I will make sure and strip the oauth code too. Thanks for the feedback
