### ISSUE TITLE
Various options greyed out

### ISSUE THREAD

**Issue by oozaru-hunter** [LaTeXing/LaTeXing#119]
I installed  Latexing via the Package manager (1.2.9).
OS is Debian Wheezy with ST3 (3065).
Under Packge Settings -> Latexing most of the entries are greyed out.
I can only click on Settings User and Default, and on the keybindings.
Also options under Tools->Packaging->Latexing are greyed out e.g. "Check system"

There is no LaTeXing folder in .config/sublime-text-3/Packages.

**Comment by csch0** [comment]
Looks like its not installed correctly by package control, could you post your console output here while starting Sublime Text?

**Comment by oozaru-hunter** [comment]
Here you go:

````
DPI scale: 1
startup, version: 3065 linux x64 channel: stable
executable: /localscratch/me/app/sublime_text_3/sublime_text
working dir: /
packages path: /net/fs01/vol/ma02/homes/me2/.config/sublime-text-3/Packages
state path: /net/fs01/vol/ma02/homes/me2/.config/sublime-text-3/Local
hardware concurrency: 4
zip path: /localscratch/me/app/sublime_text_3/Packages
zip path: /net/fs01/vol/ma02/homes/me2/.config/sublime-text-3/Installed Packages
found 5 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 3 files for base name Main.sublime-menu
loading pointer bindings
found 1 files for base name Default.sublime-theme
loading bindings
theme loaded
app ready
wrote startup cache, added files: 17 orphaned files: 0 total files: 183 cache hits: 166
pre session restore time: 0.407178
using gamma: 1 (err: 0)
startup time: 0.524358
first paint time: 0.552298
launching: /localscratch/me/app/sublime_text_3/plugin_host
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Linux SSL: _ssl module import error - /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /net/fs01/vol/ma02/homes/me2/.config/sublime-text-3/Packages/ssl-linux/st3_linux_x64/libssl-1.0.0/_ssl.cpython-33m.so)
Linux SSL: _ssl module import error - libssl.so.10: cannot open shared object file: No such file or directory
Linux SSL: _ssl module import error - libssl.so.0.9.8: cannot open shared object file: No such file or directory
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-oauthlib
reloading plugin 0_package_control_loader.50-requests
reloading plugin 0_package_control_loader.51-requests-oauthlib
reloading plugin LaTeXing.LaTeXing
loaded 899 snippets
Traceback (most recent call last):
  File "/localscratch/me/app/sublime_text_3/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/localscratch/me/app/sublime_text_3/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "LaTeXing in /net/fs01/vol/ma02/homes/me2/.config/sublime-text-3/Installed Packages/LaTeXing.sublime-package", line 4, in <module>
  File "/Development/latexing/__init__.py", line 16, in <module>
  File "/Development/latexing/cache.py", line 19, in <module>
  File "/Development/latexing/api/mendeley.py", line 9, in <module>
  File "/net/fs01/vol/ma02/homes/me2/.config/sublime-text-3/Packages/requests-oauthlib/all/requests_oauthlib/__init__.py", line 1, in <module>
    from .oauth1_auth import OAuth1
  File "/net/fs01/vol/ma02/homes/me2/.config/sublime-text-3/Packages/requests-oauthlib/all/requests_oauthlib/oauth1_auth.py", line 9, in <module>
    from requests.compat import is_py3
  File "/net/fs01/vol/ma02/homes/me2/.config/sublime-text-3/Packages/requests/all/requests/__init__.py", line 59, in <module>
    from .models import Request, Response, PreparedRequest
  File "/net/fs01/vol/ma02/homes/me2/.config/sublime-text-3/Packages/requests/all/requests/models.py", line 19, in <module>
    from .packages.urllib3.fields import RequestField
  File "/net/fs01/vol/ma02/homes/me2/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/net/fs01/vol/ma02/homes/me2/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 31, in <module>
    from .connection import (
  File "/net/fs01/vol/ma02/homes/me2/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connection.py", line 45, in <module>
    from .util.ssl_ import (
  File "/net/fs01/vol/ma02/homes/me2/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/util/__init__.py", line 5, in <module>
    from .ssl_ import (
  File "/net/fs01/vol/ma02/homes/me2/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/util/ssl_.py", line 12, in <module>
    import ssl
  File "./ssl.py", line 60, in <module>
ImportError: No module named '_ssl'
reloading plugin Package Control.Package Control
reloading plugin Package Control.bootstrap
plugins loaded
Package Control: No updated packages
````

**Comment by csch0** [comment]
So the problem here is not LaTeXing, it is the SSL library on Debian which is mandatory for LaTeXing

**Comment by oozaru-hunter** [comment]
Okay, thanks for the hint with the log. In this case it seems I cannot use Latexing.

**Comment by csch0** [comment]
Its the missing ssl library normally its working Linux, very odd but surely fixable even not by myself. I will check this later on my own in a virtual machine with Debian. So just create an issue on the ssl project and we will figure this out.

**Comment by oozaru-hunter** [comment]
I assumed it's a glibc problem, because of 
  Linux SSL: _ssl module import error - /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found
It would not be the first time I cannot use a program in Debian because of this ancient glibc version.

**Comment by csch0** [comment]
Yes so you know where to look.. :) I will add a try/catch around the import later, so you can still use LaTeXing, even if without the online functions.

**Comment by oozaru-hunter** [comment]
Sadly I dont want to upgrade glibc on this machine (no messing around with the system while writing my thesis...). 

Would be great if you could work around it :+1:

**Comment by csch0** [comment]
nah... no risk now fun.. :+1:

**Comment by escherpf** [comment]
This is precisely what is happening to me on Windows on my work computer, where LaTeXing is recognized but all options, save for settings and keybindings, are grayed out. I was missing the four new Package Control dependencies (bz2, oauthlib, requests, requests-oauthlib), and installed them manually (since they would not install automatically). 
Now I get the following log upon firing up ST3: 

```
reloading plugin LaTeXing.LaTeXing
Traceback (most recent call last):
  File "D:\Sublime Text 3075\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\Sublime Text 3075\sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "LaTeXing in D:\Sublime Text 3075\Data\Installed Packages\LaTeXing.sublime-package", line 4, in <module>
  File "/Development/latexing/__init__.py", line 16, in <module>
  File "/Development/latexing/cache.py", line 19, in <module>
  File "/Development/latexing/api/mendeley.py", line 9, in <module>
ImportError: No module named 'requests_oauthlib'
```
Even though *requests_oauthlib* which resides in *requests-oauthlib* is in my *data/packages* directory. I should also note that when I try to install anything via PC I get a SSL: CERTIFICATE_VERIFY_FAILED error. 

Is this likely an insurmountable firewall problem (as I do not have admin rights on this computer)?

**Comment by csch0** [comment]
Yes @escherpf Problem here is that Package Control created some logic to make sure the dependencies are loaded before anything else. So the problem might be a missing proxy server set?! Not really related to LaTeXing though..
