### ISSUE TITLE
Cannot autorize mendeley on linux

### ISSUE THREAD

**Issue by rudvfaden** [LaTeXing/LaTeXing#124]
I cannot the the authorization to work on linux. It works fine on mac. 

```
LTX DEBUG cite.py:93 fetch_cites {'id': 'mendeley', 'data': ['normal', 'tag', 'folder', 'missing']}
Traceback (most recent call last):
  File "/Development/latexing/api/mendeley.py", line 213, in on_done
  File "/Development/latexing/api/mendeley.py", line 42, in get_refresh_token
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests-oauthlib/all/requests_oauthlib/oauth2_session.py", line 176, in fetch_token
    verify=verify)
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests-oauthlib/all/requests_oauthlib/oauth2_session.py", line 299, in request
    headers=headers, data=data, **kwargs)
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 610, in send
    r.content
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests/all/requests/models.py", line 730, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests/all/requests/models.py", line 655, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/response.py", line 273, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/rudfaden/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/response.py", line 203, in read
    data = self._fp.read(amt)
  File "./http/client.py", line 507, in read
TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by csch0** [comment]
@rudvfaden its the same like we had in this issue #116. Don't really understand why you create a new issue then.

There you used the beta version of Freya, so best use a stable distribution and you fixed it with the last comment. So if its not working again, its an issue with your installation and not LaTeXing since it doesn't change in the last days.

**Comment by rudvfaden** [comment]
Before I could not get data from mendeley. Now, after my reinstall, I had to reenable mendely. That is, get the code from the mendeley api. Maybe it is the same issue, I am not sure

**Comment by csch0** [comment]
Its exactly the same error message you linked here, so same issue!

https://github.com/LaTeXing/LaTeXing/issues/116#issuecomment-78131079

Make sure you are copy the code from the website without a space at front and back.
