### ISSUE TITLE
latexing not compiling

### ISSUE THREAD

**Issue by sdaza** [LaTeXing/LaTeXing#163]
Hello, 
I have been using latexing for a while. I am using now the last latexing version (1.2.14). When I compile I get this: 

`[Compile ~/Documents/example.tex]`

The output folder is created, but nothing else happens.
If I compile again I get: 

`### Running process!! Cannot initiate a new one!!! Please wait or terminate the old one. ###`

Any ideas ?

```
+------------+----------+---------+---------------------------+
| Executable | Type     | Status  | Path                      |
+------------+----------+---------+---------------------------+
| perl       | required | Found   | perl                      |
| latexmk    | required | Found   | latexmk                   |
| texcount   | optional | Found   | texcount                  |
| biber      | optional | Found   | biber                     |
| bibtex     | optional | Found   | bibtex                    |
| pdflatex   | optional | Found   | pdflatex                  |
| xelatex    | optional | Found   | xelatex                   |
| lualatex   | optional | Found   | lualatex                  |
| kpsewhich  | optional | Found   | kpsewhich                 |
| texdoc     | optional | Found   | texdoc                    |
| sublime    | optional | Missing |                           |
| rscript    | optional | Found   | Rscript                   |
| skim       | viewer   | Found   | /Applications/Skim.app    |
| preview    | viewer   | Found   | /Applications/Preview.app |
+------------+----------+---------+---------------------------+

+----------------+
| Searched Path  |
+----------------+
| /usr/sbin      |
| /usr/bin       |
| /opt/local/bin |
| /bin           |
| /sbin          |
| /usr/texbin    |
| /usr/local/bin |
+----------------+
** Checked with LaTeXing 1.2.14 
```

**Comment by csch0** [comment]
Thats odd, did you adjusted the build system, I made a small change there. Could you post the console output with enabled LaTeXing log?

**Comment by sdaza** [comment]
This is what I get when I build a file:

```
LTX DEBUG terminal.py:199 find_executable latexmk True True
LTX DEBUG terminal.py:252 command_executable ['latexmk'] True
LTX DEBUG terminal.py:237 find_executable latexmk latexmk
Exception in thread Thread-12:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Development/latexing/progress.py", line 16, in run
  File "/Development/latexing/compiler.py", line 66, in <lambda>
  File "/Development/latexing/compiler.py", line 145, in on_run
  File "/Development/latexing/compiler.py", line 270, in run
  File "/Development/latexing/compiler.py", line 340, in update_remote_bibliography
  File "/Development/latexing/cite.py", line 46, in find_remote_cites
  File "/Development/latexing/cache.py", line 1128, in __init__
  File "./posixpath.py", line 142, in basename
AttributeError: 'list' object has no attribute 'rfind'

reloading Packages/User/LaTeXing.sublime-settings
```

**Comment by csch0** [comment]
Thats a problem with your global bib file, please remove it temporary for your sublime-settings to validate the problem.

**Comment by sdaza** [comment]
Yes, it was a problem with my global bib file. I have to solve now my problem with the bibliography.

**Comment by sdaza** [comment]
It is not working when I use a global  bib file :(

**Comment by csch0** [comment]
Yes that clearly needs to be fixed. Whats your path/setting??

**Comment by sdaza** [comment]
`"global_bib_file_path":  ["/Users/sdaza/Dropbox/References/sdaza.bib"]`

**Comment by csch0** [comment]
Just change it to: 

```"global_bib_file_path": "/Users/sdaza/Dropbox/References/sdaza.bib"```

.. and it should work. This was a fix/change a few season back. You could also use the following to support multiple systems.

```"global_bib_file_path": "~/Dropbox/References/sdaza.bib"```

**Comment by sdaza** [comment]
Thanks @csch0. It is working now. I still have problems with getting my references from a global bib file. Latexing doesn't read them as a remote lib, so I cannot add references "on the go".

**Comment by csch0** [comment]
Did you changed the cache option for that, or run resync after you made some changes?

**Comment by sdaza** [comment]
Once I generate the bib fie where my tex file is, latexing only reads the local file, not the global bib file. 

If I  use:  `"remote_bibliography_in_category": true` I can access to my global lib file but after going through several keystrokes :(

**Comment by sdaza** [comment]
Following the menu when `"remote_bibliography_in_category": true` also removes already cited references from the list for the global lib file. It would be great if one could access to the global file just as when using zotero or mendeley through latexing.  I am using a global file because of the problems with the latex translator (e.g., institutional authors, special characters).
