### ISSUE TITLE
Bibliography synchronisation issue (Mendeley)

### ISSUE THREAD

**Issue by dannyyy** [LaTeXing/LaTeXing#221]
I set up Mendeley synchronisation as described in your tutorial. At the beginning it was working great. Maybe after a week I got after initiating a new build the message:

> Menedley.cache outedated, would you like to synchronise the data now? The items are available for the next call! `Synchronise` or `Cancel`

If I select `Synchronise` a error appear:

> The synchronisation is already running, please wait!

Restarting SL3 or even the computer doesn't fix the problem. Two weeks ago I started with deleting every cache file I found (from the SL3 menu as well as in the file explorer) and any other related file which could have an effect on that. After a restart of SL3 Latexing was asking again for the API key (a browser window has been opened) and everything worked as expected. Until now (one week later). I haven't repeated the procedure, because it seems to be more a hack than a solution. May you can check if the API key has a expiration date? For me it's not bad to re-enter a new API key every week, if the browser windows automatically appear. But having this error and cleaning all the caches manually is bad.

The console reports this error:

> Package Control: Skipping automatic upgrade, last run at 2016-05-20 09:39:02, next run at 2016-05-20 10:39:02 or after
Exception in thread Thread-1:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Development/latexing/progress.py", line 16, in run
  File "/Development/latexing/cache.py", line 204, in cache
  File "/Development/latexing/cache.py", line 351, in cache_mendeley
  File "/Development/latexing/cache.py", line 1195, in run
  File "/Development/latexing/api/mendeley.py", line 222, in run
  File "/Development/latexing/api/mendeley.py", line 167, in run
  File "/Development/latexing/api/mendeley.py", line 36, in get_access_token
  File "C:\Users\DMEIER~1.HEI\AppData\Roaming\SUBLIM~1\Packages\REQUES~1\all\requests_oauthlib\oauth2_session.py", line 257, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Users\DMEIER~1.HEI\AppData\Roaming\SUBLIM~1\Packages\oauthlib\all\oauthlib\oauth2\rfc6749\clients\base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Users\DMEIER~1.HEI\AppData\Roaming\SUBLIM~1\Packages\oauthlib\all\oauthlib\oauth2\rfc6749\parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "C:\Users\DMEIER~1.HEI\AppData\Roaming\SUBLIM~1\Packages\oauthlib\all\oauthlib\oauth2\rfc6749\parameters.py", line 383, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "C:\Users\DMEIER~1.HEI\AppData\Roaming\SUBLIM~1\Packages\oauthlib\all\oauthlib\oauth2\rfc6749\errors.py", line 259, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Invalid grant

**Comment by bquantum** [comment]
Hi, 
I am also facing this issue. Any good solutions?

**Comment by csch0** [comment]
So far I was not able to reproduce the problem. Was it also in your system that it worked before?

Could you share some details about the used OS?

**Comment by dannyyy** [comment]
Both systems have Windows 10 and Sublime 3.

**Comment by tminea** [comment]
I have exactly the same problem here , using Ubuntu 16.04

**Comment by RicherMans** [comment]
Same problem here with Manjaro.
`Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Development/latexing/progress.py", line 16, in run
  File "/Development/latexing/cache.py", line 204, in cache
  File "/Development/latexing/cache.py", line 351, in cache_mendeley
  File "/Development/latexing/cache.py", line 1195, in run
  File "/Development/latexing/api/mendeley.py", line 222, in run
  File "/Development/latexing/api/mendeley.py", line 167, in run
  File "/Development/latexing/api/mendeley.py", line 36, in get_access_token
  File "/home/richman/.config/sublime-text-3/Packages/requests-oauthlib/all/requests_oauthlib/oauth2_session.py", line 257, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/home/richman/.config/sublime-text-3/Packages/oauthlib/all/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/home/richman/.config/sublime-text-3/Packages/oauthlib/all/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "/home/richman/.config/sublime-text-3/Packages/oauthlib/all/oauthlib/oauth2/rfc6749/parameters.py", line 383, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/home/richman/.config/sublime-text-3/Packages/oauthlib/all/oauthlib/oauth2/rfc6749/errors.py", line 259, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Invalid grant`
