### ISSUE TITLE
Latexing uninstallation crashes

### ISSUE THREAD

**Issue by Kaba2** [LaTeXing/LaTeXing#247]
Uninstalling Latexing 1.2.20 crashes under Sublime Text 3126 on Windows.

**Comment by csch0** [comment]
That's sounds like a package control issue, could be a bit more specific what's not working?

**Comment by Kaba2** [comment]
Sublime Text simply freezes. You seem to be right, I cannot remove another package either.

**Comment by Kaba2** [comment]
This was a problem with package control, which had to manually deleted from the hard-drive to recover.

**Comment by Kaba2** [comment]
On the other hand, installing Latexing produces the following error on the console:

    Traceback (most recent call last):
      File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
        m = importlib.import_module(modulename)
      File "./python3.3/importlib/__init__.py", line 90, in import_module
      File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
      File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
        exec(compile(source, source_path, 'exec'), mod.__dict__)
      File "LaTeXing in C:\Users\Kaba\AppData\Roaming\Sublime Text 3\Installed Packages\LaTeXing.sublime-package", line 4, in <module>
      File "/Development/latexing/__init__.py", line 17, in <module>
      File "/Development/latexing/cache.py", line 19, in <module>
      File "/Development/latexing/api/mendeley.py", line 9, in <module>
