### ISSUE TITLE
global_bib_file and global_bib_file_path

### ISSUE THREAD

**Issue by barik** [LaTeXing/LaTeXing#76]
Currently, it seems like the use of `global_bib_file` and `global_bib_file_path` are a little confusing. The default setting (`Settings - Default`) is:

```
"global_bib_file": false,
"global_bib_file_path": [],
```
If you set it to:

```
"global_bib_file": true,
"global_bib_file_path": ["C:/Users/tbarik/Documents/library.bib"],
```

An empty window pane appears at the bottom of the screen. When investigating the Console, it looks like a string is desired:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "./latexing/cite.py", line 395, in run
  File "./latexing/cite.py", line 87, in choose_source
  File "./latexing/cite.py", line 83, in on_done
  File "./latexing/cite.py", line 185, in fetch_cites
  File "./ntpath.py", line 309, in basename
  File "./ntpath.py", line 291, in split
TypeError: Can't convert 'list' object to str implicitly
```

Perhaps the default `global_bib_file_path` should be `""`  (empty string) instead of `[]` (empty list) to avoid this confusion?

```
"global_bib_file": false,
"global_bib_file_path": "",
```

**Comment by csch0** [comment]
Handled by #143
