### ISSUE TITLE
Insert TeX symbol not working

### ISSUE THREAD

**Issue by kacer** [LaTeXing/LaTeXing#88]
Whenewer i hit `§` or select "Insert TeX Symbol" from the command pallete, nothing happens and console shows this traceback:

```
Traceback (most recent call last):
  File "./json/decoder.py", line 368, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michal\Sublime\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "./latexing/insert.py", line 165, in run
  File "./latexing/tools.py", line 430, in load_resource
  File "./json/__init__.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded
```

Re-installation didn't help.

**Comment by kacer** [comment]
Well, as soon as I posted this issue, I noticed another one (#13) regarding this. I found empty `yourname.sublime-completions` file in my packages directory. When I deleted it, the autocomplete started to work.

**Comment by bordaigorl** [comment]
This just bit me as well with the latest version of the plugin.
It would be much more helpful if the code involved in this would be wrapped in a `try...catch` block so that the problematic files are simply ignored and maybe in the console we get a meaningful warning.
